# Generated by Django 3.0.1 on 2019-12-27 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clients',
        ),
    ]
